- .gitignore
- CMSToolBox/emailtools.py
- README.rst
- docs/toolbox.rst
- test/package_test.sh
- test/pylint.cfg
- test/test_example.py
- test/test_style.sh
I've added email to the tool box for WorkflowWebTools security developments.
> Email in central tools

- .gitignore
- PackageList.txt
- docs/conf.py
- docs/index.rst
- docs/siteadmintoolkit.rst
- test/test_style.sh
This should be merged after the CMSCompOps/SiteAdminToolkit PR is.
> Added a page for UnmergedCleaner script

- README.rst
- docs/index.rst
- docs/toolbox.rst
A minor update that is needed for the SiteAdmin webpage to properly render.
> Made references to each page.

- .travis.yml
- CMSToolBox/_webtools.py
- CMSToolBox/dashboard.py
- CMSToolBox/elasticsearch.py
- CMSToolBox/workflowinfo.py
- README.rst
- test/package_test.sh
- test/run_tests.sh
- test/test_build_docs.sh
- test/test_shell_style.sh
- test/test_style.sh
Added a static analysis tool to automatically check shell scripts for potential errors.
In addition, there is some reworked JSON fetches in CMSToolBox. It seemed silly to be fetching JSONs over and over again, so there is now a wrapper function that handles the various kinds of connections.
> Shell style

- README.rst
- docs/conf.py
- docs/customdocs.py
- docs/example.pl
- docs/example.sh
I've started down the dark path of learning Perl. This might end badly, but in the meanwhile, I've added Sphinx support to render POD comment blocks properly on our webpages.
> POD support

- install.sh
Getting the right tag wasn't working since I was cloning with no depth. This should work now.
> Directly clone the tag we want.

- CMSToolBox/reqmgrclient.py
- docs/toolbox.rst
- docs/wmagentscripts.rst
A simple client used to get information on the workflow page view.
> ReqMgrClient started.

- docs/wmagentscripts.rst
- setup.py
- test/test_build_docs.sh
Added the proposed README.rst for WmAgentScripts directly to OpsSpace for now to keep readthedocs from crashing.
Also updated the docs test to catch these sort of errors.
> WmAgentScripts docs

- docs/wmagentscripts.rst
Some of the headers were flipped, so I'm updating these for the example page.
> Some headers were flipped

- CMSToolBox/webtools.py
Requires cern-get-sso-cookies to be installed...
> Added support for sending Shibboleth sastifactory cookies.

- CMSToolBox/webtools.py
- test/test_build_docs.sh
Main update is catching ImportErrors in the Sphinx build
> Documentation

- docs/wmagentscripts.rst
This is the first update of the documentation. I picked the scripts I use regularly.
> First documentation update

- CMSToolBox/dashboard.py
- CMSToolBox/mcmclient.py
- CMSToolBox/sitereadiness.py
- CMSToolBox/workflowinfo.py
- setup.py
The most recent version of pylint for Python 2.7 has a couple additional rules to pass. In particular:
- I was overwriting input parameters to functions
- return statements nested inside else clauses
> Changes for updated pylint.

- CMSToolBox/workflowinfo.py
Created a class to hold Prep ID info for caching purposes
> Prep ID info

- CMSToolBox/siteinfo.py
Added sites and also allows determination of site using host name.
> Site domains added

- CMSToolBox/workflowinfo.py
- docs/toolbox.rst
- setup.py
Fixed the docstrings on the decorated WorkflowInfo functions.
Also bumped version in the documentation for fun.
> Function wrapping

- test/test_style.sh
Subdirectories were not properly tested before. A few scripts will need to be rewritten.
> Test style

- docs/setup.rst
- setup.py
- Fix typo in installation instructions
- Work around broken symlinks in other repositories
> Small fixes

- CMSToolBox/workflowinfo.py
Also does proper pythonic nested list comprehensions
> Added function to Info classes to reset selectively.

- .travis.yml
- CMSToolBox/workflowinfo.py
Fix for https://github.com/CMSCompOps/WorkflowWebTools/issues/100
> Pass _ECHO in site name check
